### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by DORcode** [pwillie/prometheus-es-adapter#28] opened 2019-09-16 01:15 UTC
![TIM截图20190916090514](https://user-images.githubusercontent.com/22499266/64930336-8b7b0280-d862-11e9-97c4-473e66be081f.png)

just like to pic shows, what's the problem?

it's the config in prometheus-prometheus.yml
remoteRead:
  - url: "http://prometheus-es-adapter:8000/read"
    readRecent: true
  remoteWrite:
  - url: "http://prometheus-es-adapter:8000/write"

it's the config in prometheus-es-adapter.yml
env:
        - name: ES_URL
          value: "http://elasticsearch.skywalking:9200"
        - name: ES_WORKERS
          value: "1"
        - name: ES_BATCH_MAX_AGE
          value: "10"
        - name: ES_ALIAS
          value: "prom-metrics"
        - name: ES_INDEX_MAX_AGE
          value: "1d"
        - name: ES_INDEX_MAX_DOCS
          value: "30000000"
        - name: ES_INDEX_DAILY
          value: "true"

both the promethues and prometheus-es-adapter deployed in k8s, grafana charts just displays recent metrics, the elder didn't , was the config wrong?

**Comment by pwillie** [comment] 2020-01-15 20:42
Looks like a duplicate of #9

**Closed by pwillie** 2020-01-15 20:42 UTC
